module "dev-k8s-cluster" {
  source                        = "../../modules/k8s-cluster"
  aws_account                   = "624368621157"
  aws_region                    = "eu-west-1"
  cert_cn                       = "Kubernetes"
  cert_country                  = var.cert_country
  cert_locality                 = var.cert_locality
  cert_organisation_name        = var.cert_organisation_name
  cert_organisational_unit      = var.cert_organisational_unit
  cert_state                    = var.cert_state
  ec2_ami_type_controller_node  = "ami-03046470"
  ec2_ami_type_etcd_node        = "ami-03046470"
  ec2_ami_type_worker_node      = "ami-03046470"
  ec2_instance_type             = "t2.nano"
  ec2_ssh_key_name              = "ksone"
  environment                   = "ksone"
  network_availability_zone_a   = "eu-west-1a"
  network_cluster_cidr_range    = "TODO"
  network_ip_controller_1       = var.network_ip_controller_1
  network_ip_controller_2       = var.network_ip_controller_2
  network_ip_etcd_1             = var.network_ip_etcd_1
  network_ip_etcd_2             = var.network_ip_etcd_2
  network_ip_primary_ip         = "10.0.0.1"
  network_ip_worker_1           = var.network_ip_worker_1
  network_ip_worker_2           = var.network_ip_worker_2
  network_subnet_k8s_cidr_range = "10.0.0.0/24"
  network_vpc_k8s_cidr_range    = "10.0.0.0/16"
}
