module "dev-k8s-cluster" {
  source                        = "../../terraform/modules/k8s-cluster"
  aws_account                   = "624368621157"
  aws_region                    = "eu-west-1"
  dns_etcd_srv_name             = var.dns_etcd_srv_name
  ec2_ami_type_bastion          = var.ec2_ami_type_bastion
  ec2_ami_type_controller_node  = var.ec2_ami_type_controller_node
  ec2_ami_type_etcd_node        = var.ec2_ami_type_etcd_node
  ec2_ami_type_worker_node      = var.ec2_ami_type_worker_node
  ec2_count_controller          = 3
  ec2_count_etcd                = 3
  ec2_count_worker              = 3
  ec2_instance_type             = "t2.nano"
  ec2_ssh_key_name              = "ksone"
  environment                   = "ksone"
  network_availability_zone_a   = "eu-west-1a"
  network_cluster_cidr_range    = "TODO"
  network_ip_bastion            = var.network_ip_bastion
  network_ip_controller         = var.network_ip_controller
  network_ip_worker             = var.network_ip_worker
  network_subnet_k8s_cidr_range = var.network_subnet_k8s_cidr_range
  network_vpc_k8s_cidr_range    = var.network_vpc_k8s_cidr_range
}
