module "dev-k8s-cluster" {
  source                           = "../../terraform/modules/k8s-cluster"
  aws_account                      = "624368621157"
  aws_region                       = "eu-west-1"
  dns_etcd_srv_name                = var.dns_etcd_srv_name
  ec2_ami_type_bastion             = var.ec2_ami_type_bastion
  ec2_ami_type_controller_node     = var.ec2_ami_type_controller_node
  ec2_ami_type_etcd_node           = var.ec2_ami_type_etcd_node
  ec2_ami_type_worker_node         = var.ec2_ami_type_worker_node
  ec2_count_controller             = 3
  ec2_count_etcd                   = 3
  ec2_count_worker                 = 3
  ec2_instance_type                = "t2.nano"
  ec2_ssh_key_name                 = "ksone"
  environment                      = "ksone"
  network_availability_zones       = var.network_availability_zones
  network_ip_alb                   = var.network_ip_alb
  network_ip_bastion               = var.network_ip_bastion
  network_ip_controller_mask       = var.network_ip_controller_mask
  network_ip_worker_mask           = var.network_ip_worker_mask
  network_subnet_count_private     = var.network_subnet_count_private
  network_subnet_private_cidr_mask = var.network_subnet_private_cidr_mask
  network_subnet_public_cidr_range = var.network_subnet_public_cidr_range
  network_vpc_cidr_range           = var.network_vpc_cidr_range
}
