---
#- name: control plane all
#  hosts:
#    - etcd
#    - controller
#  become: yes
#  tasks:
#    - name: delete /tmp/files
#      file:
#        state: absent
#        path: /tmp/files
#    - name: deploy /tmp/files to /tmp
#      synchronize:
#        src: ../terraform/modules/k8s-cluster/files
#        dest: /tmp
#        rsync_opts:
#          - "--chmod=F700"
#          - "--go"
#- name: etcd1
#  hosts: etcd1
#  become: yes
#  tasks:
#    - name: deploy /tmp/ansible/etcd1.service to /etc/systemd/system/etcd.service
#      copy:
#        src: /tmp/ansible/etcd1.service
#        dest: /etc/systemd/system/etcd.service
#        mode: 0600
#        force: yes
#- name: etcd2
#  hosts: etcd2
#  become: yes
#  tasks:
#    - name: deploy /tmp/ansible/etcd2.service to /etc/systemd/system/etcd.service
#      copy:
#        src: /tmp/ansible/etcd2.service
#        dest: /etc/systemd/system/etcd.service
#        mode: 0600
#        force: yes
- name: etcd-all
  hosts: etcd
  become: yes
#  tasks:
#    - name: deploy .pem files to /etc/etcd
#      copy:
#        src: "{{ item }}"
#        dest: "/etc/etcd/"
#        mode: 0600
#      with_fileglob:
#        - "*.pem"
#    - name: ensure /tmp/files/etcd/ exists
#      become: true
#      ansible.builtin.file:
#        path: /tmp/files/etcd
#        state: directory
#        mode: 0700
#    - name: deploy /tmp/files/etcd/install-etcd.sh to /tmp/files/etcd/install-etcd.sh
#      become: true
#      copy:
#        src: ../terraform/modules/k8s-cluster/files/etcd/install-etcd.sh
#        dest: /tmp/files/etcd/install-etcd.sh
#        mode: 0700
#        force: yes
#    - name: execute /tmp/files/etcd/install-etcd.sh
#      become: true
#      script: /tmp/files/etcd/install-etcd.sh
- name: controllers-all
  hosts: controller
  become: yes
  tasks:
    - name: ensure /var/lib/kubernetes exists
      become: true
      ansible.builtin.file:
        path: /var/lib/kubernetes
        state: directory
        mode: 0700
    - name: deploy .pem files to /var/lib/kubernetes
      copy:
        src: "{{ item }}"
        dest: "/var/lib/kubernetes"
        mode: 0600
      with_fileglob:
        - "*.pem"
    - name: ensure /tmp/files/controller/ exists
      become: true
      ansible.builtin.file:
        path: /tmp/files/controller
        state: directory
        mode: 0700
    - name: deploy /tmp/files/controller/ to /tmp/files/controller
      become: true
      copy:
        src: ../terraform/modules/k8s-cluster/files/controller/
        dest: /tmp/files/controller
        mode: 0700
        force: yes
    - name: execute /tmp/files/controller/install-controller.sh
      become: true
      script: /tmp/files/controller/install-controller.sh
    - name: execute /tmp/files/controller/install-authentication.sh
      become: true
      script: /tmp/files/controller/install-authentication.sh
    - name: execute /tmp/files/controller/install-authorisation.sh
      become: true
      script: /tmp/files/controller/install-authorisation.sh
