---
  - name: k8s-setup
    hosts: etcd
    become: yes
    tasks:
      - name: deploy .pem files to /etc/etcd
        copy:
          src: "{{ item }}"
          dest: "/etc/etcd/"
          mode: 0600
        with_fileglob:
          - "*.pem"
      - name: deploy /tmp/ansible/etcd.service to /etc/systemd/system/
        copy:
          src: /tmp/etcd/etcd.service
          dest: /etc/systemd/system
          mode: 0600
          force: yes
      - name: ensure /tmp/etcd/ exists
        become: true
        ansible.builtin.file:
          path: /tmp/etcd
          state: directory
          mode: 0700
      - name: deploy /tmp/etcd/install-etcd.sh to /tmp/etcd/install-etcd.sh
        become: true
        copy:
          src: /tmp/etcd/install-etcd.sh
          dest: /tmp/etcd/install-etcd.sh
          mode: 0700
          force: yes
      - name: execute /tmp/etcd/install-etcd.sh
        become: true
        script: /tmp/etcd/install-etcd.sh
